name: CCNA Lab Validation

on:
  push:
    branches:
      - testing

jobs:
  validate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Count README Files
        run: |
          count=$(find . -name "README.md" | wc -l)
          echo "README files found: $count"

      - name: Validate Packet Tracer Files
        run: |
          count=$(find . -name "*.pkt" | wc -l)

          if [ "$count" -eq 0 ]; then
            echo "No Packet Tracer files found!"
            exit 1
          fi

          echo "PKT files found: $count"

      - name: Count PNG Files
        run: |
          count=$(find . -name "*.png" | wc -l)
          echo "PNG files found: $count"

      - name: Validation Complete
        run: echo "CCNA Lab Validation Passed"