name: CCNA Lab Validation

on:
  push:
    branches:
      - testing

jobs:
  validate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Count README Files
        run: |
          echo "README files found:"
          find . -name "README.md" | wc -l

      - name: Count Packet Tracer Files
        run: |
          echo "PKT files found:"
          find . -name "*.pkt" | wc -l

      - name: Count PNG Files
        run: |
          echo "PNG files found:"
          find . -name "*.png" | wc -l